name: EconomyPlugin
version: '1.0'
main: de.zkinqjustin.economyPlugin.EconomyPlugin
api-version: '1.20'
depend: ["Vault"]
softdepend: ["PlaceholderAPI"]
commands:
  balance:
    description: Zeigt deinen Kontostand
    aliases: [bal, money]
  pay:
    description: Überweise Geld an einen anderen Spieler
  balanceadd:
    description: Fügt einem Spieler Geld hinzu
    usage: /balanceadd <spieler> <betrag>
    permission: economy.balanceadd
  bank:
    description: Bank-Befehle
    usage: /bank [deposit/withdraw] [Betrag]
    aliases: [banking]
